# Generated by Django 3.2.2 on 2021-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('o_id', models.CharField(blank=True, max_length=100, null=True)),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('option_1', models.TextField(blank=True, null=True)),
                ('option_2', models.TextField(blank=True, null=True)),
                ('option_3', models.TextField(blank=True, null=True)),
                ('option_4', models.TextField(blank=True, null=True)),
                ('option_5', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('hints', models.TextField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_subject', models.CharField(blank=True, max_length=450, null=True)),
                ('exam_year', models.CharField(blank=True, max_length=350, null=True)),
                ('other_exam', models.CharField(blank=True, max_length=500, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='offline_quiz/')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('C', 'Correct & Published'), ('N', 'Need to Modify')], default='P', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
