# Generated by Django 3.2.2 on 2021-05-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210510_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='exam_year',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='media',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
