# Generated by Django 3.2.2 on 2021-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210516_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='explanation/'),
        ),
    ]
