# Generated by Django 3.2.2 on 2021-05-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210518_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='other_exam',
            field=models.CharField(blank=True, help_text='write the exam list here', max_length=500, null=True),
        ),
    ]
