# Generated by Django 3.2.2 on 2021-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210530_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
